# Ansible inventory created from ['/home/ubuntu/HLD_ARD_Network_Architecte/topology_ibn_lab.yml', 'package:topology-defaults.yml']
#

all:
  hosts: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
dmz_stubs:
  hosts:
    srv_ad: {}
    srv_dns: {}
dmzfw_pair:
  hosts:
    dmzfw1: {}
    dmzfw2: {}
linux:
  hosts:
    host_employee:
      ansible_host: clab-HLDARDNetwor-host_employee
      id: 5
    host_guest:
      ansible_host: clab-HLDARDNetwor-host_guest
      id: 6
    host_iot:
      ansible_host: clab-HLDARDNetwor-host_iot
      id: 7
    internet:
      ansible_host: clab-HLDARDNetwor-internet
      id: 11
    jumphost:
      ansible_host: clab-HLDARDNetwor-jumphost
      id: 10
    srv_ad:
      ansible_host: clab-HLDARDNetwor-srv_ad
      id: 9
    srv_dns:
      ansible_host: clab-HLDARDNetwor-srv_dns
      id: 8
modules:
  hosts:
    dmzfw1: {}
    dmzfw2: {}
    host_employee: {}
    host_guest: {}
    host_iot: {}
    internet: {}
    jumphost: {}
    srv_ad: {}
    srv_dns: {}
    usf1: {}
    usf2: {}
netlab_no_reload:
  hosts:
    host_employee: {}
    host_guest: {}
    host_iot: {}
    internet: {}
    jumphost: {}
    srv_ad: {}
    srv_dns: {}
netlab_ready_ansible:
  hosts:
    dmzfw1: {}
    dmzfw2: {}
    usf1: {}
    usf2: {}
unprovisioned:
  hosts: {}
user_hosts:
  hosts:
    host_employee: {}
    host_guest: {}
    host_iot: {}
usf_pair:
  hosts:
    usf1: {}
    usf2: {}
vyos:
  hosts:
    dmzfw1:
      ansible_host: clab-HLDARDNetwor-dmzfw1
      id: 3
    dmzfw2:
      ansible_host: clab-HLDARDNetwor-dmzfw2
      id: 4
    usf1:
      ansible_host: clab-HLDARDNetwor-usf1
      id: 1
    usf2:
      ansible_host: clab-HLDARDNetwor-usf2
      id: 2
